services:
  db:
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: operarios_db
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
    driver: local