spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:mydb
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  flyway:
    enabled: false
  jpa:
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      mode: always
      data-locations: classpath:db/h2/data.sql
