spring:
  application:
    name: bompastor-api
  profiles:
    active: h2
  docker:
    compose:
      enabled: false
jwt:
  public:
    key: classpath:security/app.pub
  private:
    key: classpath:security/app.key
