spring:
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://${HOST:localhost}:5432/operarios_db
  docker:
    compose:
      enabled: true
  jpa:
    show-sql: true
