spring:
  application:
    name: operarios-api
  profiles:
    active: h2
  docker:
    compose:
      enabled: false
  h2:
    console:
      enabled: false
jwt:
  public:
    key: classpath:security/app.pub
  private:
    key: classpath:security/app.key
firebase:
  service:
    account: classpath:security/service.json
