spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:mydb
    driverClassName: org.h2.Driver
  flyway:
    enabled: false
  jpa:
    defer-datasource-initialization: true
    show-sql: true
#    hibernate:
#      ddl-auto: none
#      console.enabled: true
  sql:
    init:
      mode: always
#      schema-locations: classpath:db/h2/schema.sql
      data-locations: classpath:db/h2/data.sql
